// File __EUNIT_TestControl_%File%.cpp generated by E-UNIT program

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}

